version: "3.1"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - $PORT:8080
      - 50000:50000
    volumes:
      - jenkins-home:/var/jenkins_home
  jenkins-backup:
    image: jagiles/jenkins-backup:latest
    volumes:
      - jenkins-home:/var/jenkins_home
      - ./backups:/var/backups

volumes:
  jenkins-home:
